FROM docker.io/library/python:3.12-slim

RUN pip install streamlit requests

WORKDIR /app
COPY ui/app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]
